{{- if .Values.managementApi.kedaAutoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "shopping-system.management-api.fullname" . }}
  labels:
    {{- include "shopping-system.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "shopping-system.management-api.fullname" . }}
  minReplicaCount: {{ .Values.managementApi.kedaAutoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.managementApi.kedaAutoscaling.maxReplicas }}
  pollingInterval: {{ .Values.managementApi.kedaAutoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.managementApi.kedaAutoscaling.cooldownPeriod }}
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: {{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc:{{ .Values.kafka.service.ports.client }}
        topic: {{ (index .Values.kafka.provisioning.topics 0).name }}
        consumerGroup: {{ .Values.managementApi.config.kafka.consumerGroup }}
        lagThreshold: "{{ .Values.managementApi.kedaAutoscaling.kafkaLagThreshold }}"
{{- end }}
