{{- if .Values.kedaAutoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "management-api.fullname" . }}
  labels:
    {{- include "management-api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "management-api.fullname" . }}
  minReplicaCount: {{ .Values.kedaAutoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.kedaAutoscaling.maxReplicas }}
  pollingInterval: {{ .Values.kedaAutoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.kedaAutoscaling.cooldownPeriod }}
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: {{ .Values.config.kafka.bootstrapServers }}
        topic: {{ .Values.config.kafka.topic }}
        consumerGroup: {{ .Values.config.kafka.consumerGroup }}
        lagThreshold: {{ .Values.kedaAutoscaling.kafkaLagThreshold }}
{{- end }}
